import { db } from '@/lib/db';

async function main() {
  // Seed categories
  const categories = await Promise.all([
    db.category.upsert({
      where: { slug: 'elektronik' },
      update: {},
      create: {
        name: 'Elektronik',
        slug: 'elektronik',
        description: 'Gadget, smartphone, laptop, dan perangkat elektronik lainnya',
        icon: 'Smartphone',
        image: '/images/categories/elektronik.png',
        order: 1,
      },
    }),
    db.category.upsert({
      where: { slug: 'fashion-pria' },
      update: {},
      create: {
        name: 'Fashion Pria',
        slug: 'fashion-pria',
        description: 'Pakaian, sepatu, dan aksesoris pria',
        icon: 'Shirt',
        image: '/images/categories/fashion-pria.png',
        order: 2,
      },
    }),
    db.category.upsert({
      where: { slug: 'fashion-wanita' },
      update: {},
      create: {
        name: 'Fashion Wanita',
        slug: 'fashion-wanita',
        description: 'Pakaian, tas, sepatu, dan aksesoris wanita',
        icon: 'ShoppingBag',
        image: '/images/categories/fashion-wanita.png',
        order: 3,
      },
    }),
    db.category.upsert({
      where: { slug: 'makanan-minuman' },
      update: {},
      create: {
        name: 'Makanan & Minuman',
        slug: 'makanan-minuman',
        description: 'Makanan ringan, minuman, bumbu, dan kebutuhan dapur',
        icon: 'UtensilsCrossed',
        image: '/images/categories/makanan.png',
        order: 4,
      },
    }),
    db.category.upsert({
      where: { slug: 'kesehatan-kecantikan' },
      update: {},
      create: {
        name: 'Kesehatan & Kecantikan',
        slug: 'kesehatan-kecantikan',
        description: 'Skincare, makeup, vitamin, dan produk kesehatan',
        icon: 'Heart',
        image: '/images/categories/kecantikan.png',
        order: 5,
      },
    }),
    db.category.upsert({
      where: { slug: 'rumah-tangga' },
      update: {},
      create: {
        name: 'Rumah Tangga',
        slug: 'rumah-tangga',
        description: 'Peralatan dapur, kebersihan, dan dekorasi rumah',
        icon: 'Home',
        image: '/images/categories/rumah-tangga.png',
        order: 6,
      },
    }),
    db.category.upsert({
      where: { slug: 'olahraga' },
      update: {},
      create: {
        name: 'Olahraga',
        slug: 'olahraga',
        description: 'Alat olahraga, sepatu olahraga, dan fitness',
        icon: 'Dumbbell',
        image: '/images/categories/olahraga.png',
        order: 7,
      },
    }),
    db.category.upsert({
      where: { slug: 'atk-kantor' },
      update: {},
      create: {
        name: 'ATK & Kantor',
        slug: 'atk-kantor',
        description: 'Alat tulis, perlengkapan kantor, dan kebutuhan bisnis',
        icon: 'Pencil',
        image: '/images/categories/atk.png',
        order: 8,
      },
    }),
  ]);

  // Seed products
  const products = [
    // Elektronik
    {
      name: 'Smartphone Pro Max 5G',
      slug: 'smartphone-pro-max-5g',
      description: 'Smartphone flagship dengan prosesor terbaru, kamera 108MP, layar AMOLED 6.7 inch, baterai 5000mAh. Cocok untuk grosir dengan harga kompetitif.',
      price: 8500000,
      wholesalePrice: 7200000,
      minOrder: 5,
      stock: 150,
      images: '/images/products/smartphone-1.png',
      categoryId: categories[0].id,
      rating: 4.8,
      reviewCount: 234,
      sold: 1520,
      featured: true,
      tags: 'smartphone,5g,flagship',
      weight: '200g',
      dimensions: '16.5 x 7.6 x 0.8 cm',
    },
    {
      name: 'Laptop Ultra Slim 14"',
      slug: 'laptop-ultra-slim-14',
      description: 'Laptop tipis ringan dengan prosesor Intel Core i7 generasi terbaru, RAM 16GB, SSD 512GB. Ideal untuk bisnis dan produktivitas.',
      price: 12500000,
      wholesalePrice: 10800000,
      minOrder: 3,
      stock: 80,
      images: '/images/products/laptop-1.png',
      categoryId: categories[0].id,
      rating: 4.7,
      reviewCount: 156,
      sold: 890,
      featured: true,
      tags: 'laptop,ultrabook,business',
      weight: '1.3kg',
      dimensions: '32 x 22 x 1.6 cm',
    },
    {
      name: 'Headphone Bluetooth Premium',
      slug: 'headphone-bluetooth-premium',
      description: 'Headphone wireless dengan Active Noise Cancelling, bass mendalam, baterai 40 jam. Kualitas suara premium untuk musik dan panggilan.',
      price: 1200000,
      wholesalePrice: 850000,
      minOrder: 10,
      stock: 300,
      images: '/images/products/headphone-1.png',
      categoryId: categories[0].id,
      rating: 4.6,
      reviewCount: 412,
      sold: 3200,
      featured: false,
      tags: 'headphone,bluetooth,anc',
      weight: '250g',
      dimensions: '20 x 18 x 8 cm',
    },
    // Fashion Pria
    {
      name: 'Kemeja Formal Premium',
      slug: 'kemeja-formal-premium',
      description: 'Kemeja formal bahan katun premium, nyaman dipakai sehari-hari. Tersedia dalam berbagai warna dan ukuran. Cocok untuk seragam kantor.',
      price: 185000,
      wholesalePrice: 125000,
      minOrder: 24,
      stock: 500,
      images: '/images/products/kemeja-pria-1.png',
      categoryId: categories[1].id,
      rating: 4.5,
      reviewCount: 567,
      sold: 5600,
      featured: true,
      tags: 'kemeja,formal,pria',
      weight: '200g',
      dimensions: 'S/M/L/XL/XXL',
    },
    {
      name: 'Celana Chino Slim Fit',
      slug: 'celana-chino-slim-fit',
      description: 'Celana chino slim fit dengan bahan stretch yang nyaman. Cocok untuk kasual dan semi-formal. Warna-warna trendi.',
      price: 165000,
      wholesalePrice: 110000,
      minOrder: 24,
      stock: 450,
      images: '/images/products/celana-pria-1.png',
      categoryId: categories[1].id,
      rating: 4.4,
      reviewCount: 389,
      sold: 4200,
      featured: false,
      tags: 'celana,chino,slimfit',
      weight: '300g',
      dimensions: '28-36',
    },
    // Fashion Wanita
    {
      name: 'Dress Elegant Premium',
      slug: 'dress-elegant-premium',
      description: 'Dress elegan dengan bahan premium dan detail bordir. Cocok untuk acara formal dan pesta. Desain modern dan trendy.',
      price: 285000,
      wholesalePrice: 195000,
      minOrder: 12,
      stock: 200,
      images: '/images/products/dress-wanita-1.png',
      categoryId: categories[2].id,
      rating: 4.7,
      reviewCount: 298,
      sold: 2100,
      featured: true,
      tags: 'dress,elegant,wanita',
      weight: '250g',
      dimensions: 'S/M/L/XL',
    },
    {
      name: 'Tas Kulit Premium',
      slug: 'tas-kulit-premium',
      description: 'Tas wanita bahan kulit sintetis premium, desain elegan dan fungsional. Banyak kompartemen untuk barang bawaan.',
      price: 350000,
      wholesalePrice: 245000,
      minOrder: 10,
      stock: 180,
      images: '/images/products/tas-wanita-1.png',
      categoryId: categories[2].id,
      rating: 4.6,
      reviewCount: 234,
      sold: 1800,
      featured: true,
      tags: 'tas,kulit,wanita',
      weight: '500g',
      dimensions: '30 x 25 x 12 cm',
    },
    {
      name: 'Sepatu Heels Elegant',
      slug: 'sepatu-heels-elegant',
      description: 'Sepatu heels elegan dengan desain modern, nyaman dipakai seharian. Sol anti-slip, bahan berkualitas tinggi.',
      price: 275000,
      wholesalePrice: 190000,
      minOrder: 12,
      stock: 250,
      images: '/images/products/sepatu-wanita-1.png',
      categoryId: categories[2].id,
      rating: 4.3,
      reviewCount: 178,
      sold: 1500,
      featured: false,
      tags: 'sepatu,heels,wanita',
      weight: '350g',
      dimensions: '36-41',
    },
    // Makanan & Minuman
    {
      name: 'Kopi Arabica Premium 1kg',
      slug: 'kopi-arabica-premium-1kg',
      description: 'Biji kopi arabica pilihan dari dataran tinggi Indonesia. Roasting sempurna, aroma khas, rasa premium. Packaging kiloan.',
      price: 145000,
      wholesalePrice: 95000,
      minOrder: 20,
      stock: 400,
      images: '/images/products/kopi-1.png',
      categoryId: categories[3].id,
      rating: 4.9,
      reviewCount: 678,
      sold: 8900,
      featured: true,
      tags: 'kopi,arabica,premium',
      weight: '1kg',
      dimensions: '25 x 15 x 10 cm',
    },
    {
      name: 'Paket Snack Nusantara',
      slug: 'paket-snack-nusantara',
      description: 'Paket snack khas nusantara berisi 20 varian. Cocok untuk oleh-oleh dan stok toko. Harga grosir terjangkau.',
      price: 85000,
      wholesalePrice: 55000,
      minOrder: 50,
      stock: 600,
      images: '/images/products/snack-1.png',
      categoryId: categories[3].id,
      rating: 4.5,
      reviewCount: 456,
      sold: 7200,
      featured: false,
      tags: 'snack,nusantara,oleh-oleh',
      weight: '2kg',
      dimensions: '40 x 30 x 20 cm',
    },
    {
      name: 'Minuman Teh Botol Premium',
      slug: 'minuman-teh-botol-premium',
      description: 'Teh botol premium rasa original, green tea, dan lemon. 1 dus isi 24 botol. Segar dan menyehatkan.',
      price: 72000,
      wholesalePrice: 52000,
      minOrder: 30,
      stock: 800,
      images: '/images/products/minuman-1.png',
      categoryId: categories[3].id,
      rating: 4.4,
      reviewCount: 234,
      sold: 5600,
      featured: false,
      tags: 'minuman,teh,botol',
      weight: '12kg',
      dimensions: '40 x 30 x 25 cm',
    },
    // Kesehatan & Kecantikan
    {
      name: 'Skincare Set Lengkap',
      slug: 'skincare-set-lengkap',
      description: 'Set perawatan kulit lengkap: cleanser, toner, serum, moisturizer, sunscreen. Untuk semua jenis kulit. BPOM certified.',
      price: 320000,
      wholesalePrice: 215000,
      minOrder: 10,
      stock: 200,
      images: '/images/products/skincare-1.png',
      categoryId: categories[4].id,
      rating: 4.8,
      reviewCount: 512,
      sold: 4500,
      featured: true,
      tags: 'skincare,set,beauty',
      weight: '500g',
      dimensions: '25 x 20 x 15 cm',
    },
    {
      name: 'Makeup Kit Professional',
      slug: 'makeup-kit-professional',
      description: 'Makeup kit profesional berisi palette eyeshadow, lipstick set, foundation, dan brush set. Kualitas premium.',
      price: 450000,
      wholesalePrice: 320000,
      minOrder: 8,
      stock: 150,
      images: '/images/products/makeup-1.png',
      categoryId: categories[4].id,
      rating: 4.7,
      reviewCount: 289,
      sold: 2100,
      featured: false,
      tags: 'makeup,professional,beauty',
      weight: '600g',
      dimensions: '30 x 25 x 15 cm',
    },
    {
      name: 'Vitamin & Supplement Pack',
      slug: 'vitamin-supplement-pack',
      description: 'Paket vitamin dan suplemen: Vitamin C, D3, Omega-3, Multivitamin. BPOM dan GMP certified. Untuk daya tahan tubuh.',
      price: 195000,
      wholesalePrice: 135000,
      minOrder: 20,
      stock: 350,
      images: '/images/products/vitamin-1.png',
      categoryId: categories[4].id,
      rating: 4.6,
      reviewCount: 345,
      sold: 3800,
      featured: true,
      tags: 'vitamin,supplement,health',
      weight: '400g',
      dimensions: '20 x 15 x 12 cm',
    },
    // Rumah Tangga
    {
      name: 'Set Panci Stainless Steel',
      slug: 'set-panci-stainless-steel',
      description: 'Set panci stainless steel 5 pcs lengkap dengan tutup kaca. Bahan food grade, tahan lama, dan mudah dibersihkan.',
      price: 450000,
      wholesalePrice: 320000,
      minOrder: 6,
      stock: 120,
      images: '/images/products/panci-1.png',
      categoryId: categories[5].id,
      rating: 4.5,
      reviewCount: 234,
      sold: 1800,
      featured: false,
      tags: 'panci,stainless,dapur',
      weight: '3.5kg',
      dimensions: '45 x 30 x 25 cm',
    },
    {
      name: 'Paket Alat Kebersihan Lengkap',
      slug: 'paket-alat-kebersihan-lengkap',
      description: 'Paket lengkap alat kebersihan: sapu, pel, ember, sikat, dan cairan pembersih. Untuk rumah dan kantor.',
      price: 125000,
      wholesalePrice: 80000,
      minOrder: 20,
      stock: 400,
      images: '/images/products/alat-kebersihan-1.png',
      categoryId: categories[5].id,
      rating: 4.3,
      reviewCount: 189,
      sold: 2400,
      featured: false,
      tags: 'kebersihan,rumah,alat',
      weight: '4kg',
      dimensions: '50 x 30 x 20 cm',
    },
    {
      name: 'Dekorasi Rumah Minimalis Set',
      slug: 'dekorasi-rumah-minimalis-set',
      description: 'Set dekorasi rumah minimalis: vas bunga, lilin aromaterapi, frame foto, dan rak dinding. Desain Scandinavian.',
      price: 275000,
      wholesalePrice: 185000,
      minOrder: 10,
      stock: 180,
      images: '/images/products/dekorasi-1.png',
      categoryId: categories[5].id,
      rating: 4.6,
      reviewCount: 156,
      sold: 1200,
      featured: true,
      tags: 'dekorasi,minimalis,rumah',
      weight: '2kg',
      dimensions: '35 x 25 x 20 cm',
    },
    // Olahraga
    {
      name: 'Sepatu Running Professional',
      slug: 'sepatu-running-professional',
      description: 'Sepatu lari profesional dengan teknologi cushioning terbaru. Ringan, breathable, dan nyaman untuk lari jarak jauh.',
      price: 550000,
      wholesalePrice: 395000,
      minOrder: 12,
      stock: 200,
      images: '/images/products/sepatu-olahraga-1.png',
      categoryId: categories[6].id,
      rating: 4.7,
      reviewCount: 423,
      sold: 3200,
      featured: true,
      tags: 'sepatu,running,olahraga',
      weight: '300g',
      dimensions: '39-44',
    },
    {
      name: 'Set Dumbell Adjustable 20kg',
      slug: 'set-dumbell-adjustable-20kg',
      description: 'Set dumbell adjustable 20kg per pasang. Bahan chrome premium, grip anti-slip. Cocok untuk home gym.',
      price: 385000,
      wholesalePrice: 275000,
      minOrder: 8,
      stock: 100,
      images: '/images/products/dumbell-1.png',
      categoryId: categories[6].id,
      rating: 4.5,
      reviewCount: 198,
      sold: 980,
      featured: false,
      tags: 'dumbell,fitness,gym',
      weight: '20kg',
      dimensions: '35 x 20 x 15 cm',
    },
    // ATK & Kantor
    {
      name: 'Paket ATK Kantor Lengkap',
      slug: 'paket-atk-kantor-lengkap',
      description: 'Paket alat tulis kantor lengkap 100+ items: pulpen, pensil, buku tulis, map, stapler, dan lainnya. Untuk kebutuhan kantor.',
      price: 95000,
      wholesalePrice: 62000,
      minOrder: 30,
      stock: 500,
      images: '/images/products/alat-tulis-1.png',
      categoryId: categories[7].id,
      rating: 4.4,
      reviewCount: 267,
      sold: 4100,
      featured: false,
      tags: 'atk,kantor,alat-tulis',
      weight: '3kg',
      dimensions: '40 x 30 x 20 cm',
    },
  ];

  for (const product of products) {
    await db.product.upsert({
      where: { slug: product.slug },
      update: {},
      create: product,
    });
  }

  console.log('✅ Seed completed successfully!');
  console.log(`📦 Created ${categories.length} categories`);
  console.log(`📦 Created ${products.length} products`);
}

main()
  .catch(console.error)
  .finally(() => db.$disconnect());
