import { PrismaClient } from '@prisma/client';
const db = new PrismaClient();

async function main() {
  // Clean up old data first
  await db.orderItem.deleteMany();
  await db.order.deleteMany();
  await db.cartItem.deleteMany();
  await db.product.deleteMany();
  await db.category.deleteMany();

  // Seed categories (5 categories - Remaja removed)
  const categories = await Promise.all([
    db.category.create({
      data: {
        name: 'Bayi (0-12 Bulan)',
        slug: 'bayi-0-12-bulan',
        description: 'Baju bayi, romper, set bayi lucu dan nyaman untuk si kecil',
        icon: 'Baby',
        image: '/images/categories/bayi.png',
        order: 1,
      },
    }),
    db.category.create({
      data: {
        name: 'Balita (1-5 Tahun)',
        slug: 'balita-1-5-tahun',
        description: 'Pakaian balita lucu dan nyaman untuk aktif bermain',
        icon: 'Smile',
        image: '/images/categories/balita.png',
        order: 2,
      },
    }),
    db.category.create({
      data: {
        name: 'Anak-anak (6-12 Tahun)',
        slug: 'anak-anak-6-12-tahun',
        description: 'Baju anak untuk sekolah dan santai, model trendi dan nyaman',
        icon: 'GraduationCap',
        image: '/images/categories/anak-anak.png',
        order: 3,
      },
    }),
    db.category.create({
      data: {
        name: 'Aksesoris Baby Kids',
        slug: 'aksesoris-baby-kids',
        description: 'Topi, tas, ikat rambut, dan aksesoris lucu untuk bayi dan anak',
        icon: 'Crown',
        image: '/images/categories/aksesoris.png',
        order: 4,
      },
    }),
    db.category.create({
      data: {
        name: 'Sepatu',
        slug: 'sepatu',
        description: 'Sepatu sekolah, santai, dan olahraga untuk bayi dan anak',
        icon: 'Footprints',
        image: '/images/categories/sepatu.png',
        order: 5,
      },
    }),
  ]);

  // Seed products
  const products = [
    // === BAYI (0-12 Bulan) ===
    {
      name: 'Romper Bayi Set 3in1 Karakter Lucu',
      slug: 'romper-bayi-set-3in1-karakter-lucu',
      description: 'Set romper bayi 3in1 dengan motif karakter hewan lucu. Bahan katun stretch yang lembut dan aman untuk kulit bayi. Mudah dipakai dan dilepas dengan kancing press. Tersedia ukuran 0-6 bulan, 6-12 bulan. Cocok untuk hadiah bayi baru lahir.',
      price: 125000,
      wholesalePrice: 75000,
      minOrder: 12,
      stock: 500,
      images: '/images/products/romper-bayi.png',
      categoryId: categories[0].id,
      rating: 4.9,
      reviewCount: 456,
      sold: 6800,
      featured: true,
      tags: 'romper,bayi,set,lucu,katun',
      weight: '150g',
      sizes: '0-6B,6-12B',
    },
    {
      name: 'Set Baju Bayi Laki-Laki Casual',
      slug: 'set-baju-bayi-laki-laki-casual',
      description: 'Set baju bayi laki-laki terdiri dari kaos dan celana. Bahan katun combed 30s yang adem dan nyaman. Motif strip dan karikaturnya ganteng. Elastis di pinggang untuk kenyamanan bayi.',
      price: 95000,
      wholesalePrice: 58000,
      minOrder: 12,
      stock: 400,
      images: '/images/products/set-bayi-laki.png',
      categoryId: categories[0].id,
      rating: 4.8,
      reviewCount: 312,
      sold: 4500,
      featured: true,
      tags: 'set,bayi,laki-laki,casual,katun',
      weight: '120g',
      sizes: '0-6B,6-12B',
    },
    {
      name: 'Dress Bayi Perempuan Floral',
      slug: 'dress-bayi-perempuan-floral',
      description: 'Dress bayi perempuan motif bunga yang cantik dan feminin. Bahan katun rayon yang sejuk dan lembut. Dilengkapi dengan pita dan ruffle di bagian dada. Cocok untuk pesta dan acara spesial si kecil.',
      price: 110000,
      wholesalePrice: 68000,
      minOrder: 12,
      stock: 350,
      images: '/images/products/dress-bayi.png',
      categoryId: categories[0].id,
      rating: 4.9,
      reviewCount: 289,
      sold: 3900,
      featured: true,
      tags: 'dress,bayi,perempuan,floral,pesta',
      weight: '130g',
      sizes: '0-6B,6-12B',
    },
    {
      name: 'Jumpsuit Bayi Unisex Cotton',
      slug: 'jumpsuit-bayi-unisex-cotton',
      description: 'Jumpsuit bayi unisex bahan katun premium yang lembut dan menyerap keringat. Desain simpel dan nyaman untuk harian. Kancing press di bagian bawah untuk mudah ganti popok.',
      price: 85000,
      wholesalePrice: 50000,
      minOrder: 12,
      stock: 450,
      images: '/images/products/jaket-anak.png',
      categoryId: categories[0].id,
      rating: 4.7,
      reviewCount: 198,
      sold: 2800,
      featured: false,
      tags: 'jumpsuit,bayi,unisex,cotton,harian',
      weight: '130g',
      sizes: '0-6B,6-12B',
    },

    // === BALITA (1-5 Tahun) ===
    {
      name: 'Set Baju Balita Laki-Laki Kartun',
      slug: 'set-baju-balita-laki-laki-kartun',
      description: 'Set baju balita laki-laki motif kartun superhero dan dinosaurus. Bahan katun combed yang adem dan tidak panas. Jahitan rapi dan aman untuk anak. Cocok untuk harian dan bermain.',
      price: 105000,
      wholesalePrice: 62000,
      minOrder: 12,
      stock: 450,
      images: '/images/products/baju-balita-laki.png',
      categoryId: categories[1].id,
      rating: 4.7,
      reviewCount: 378,
      sold: 5200,
      featured: true,
      tags: 'set,balita,laki-laki,kartun,katun',
      weight: '150g',
      sizes: '1T,2T,3T,4T,5T',
    },
    {
      name: 'Dress Balita Perempuan Princess Tutu',
      slug: 'dress-balita-perempuan-princess-tutu',
      description: 'Dress balita gaya princess dengan rok tutu yang mengembang. Bahan atas katun dan rok tulle lembut. Cocok untuk pesta ulang tahun dan photo session. Warna pastel yang cantik.',
      price: 145000,
      wholesalePrice: 92000,
      minOrder: 10,
      stock: 300,
      images: '/images/products/dress-balita.png',
      categoryId: categories[1].id,
      rating: 4.9,
      reviewCount: 423,
      sold: 4800,
      featured: true,
      tags: 'dress,balita,princess,tutu,pesta',
      weight: '200g',
      sizes: '1T,2T,3T,4T,5T',
    },
    {
      name: 'Set Baju Balita Unisex Casual',
      slug: 'set-baju-balita-unisex-casual',
      description: 'Set baju balita unisex cocok untuk laki-laki dan perempuan. Desain minimalis modern dengan warna-warna ceria. Bahan cotton combed adem dan menyerap keringat. Easy wash dan tidak mudah luntur.',
      price: 90000,
      wholesalePrice: 54000,
      minOrder: 12,
      stock: 500,
      images: '/images/products/set-balita.png',
      categoryId: categories[1].id,
      rating: 4.6,
      reviewCount: 267,
      sold: 3600,
      featured: false,
      tags: 'set,balita,unisex,casual,cotton',
      weight: '140g',
      sizes: '1T,2T,3T,4T,5T',
    },
    {
      name: 'Kaos Balita Print Kartun Lucu',
      slug: 'kaos-balita-print-kartun-lucu',
      description: 'Kaos balita dengan print kartun lucu dan warna ceria. Bahan cotton combed 24s yang lembut dan adem. Sablon rubber yang aman dan tidak luntur. Tersedia 15+ motif pilihan.',
      price: 65000,
      wholesalePrice: 38000,
      minOrder: 24,
      stock: 600,
      images: '/images/products/kaos-anak.png',
      categoryId: categories[1].id,
      rating: 4.5,
      reviewCount: 312,
      sold: 5600,
      featured: false,
      tags: 'kaos,balita,kartun,cotton,lucu',
      weight: '110g',
      sizes: '1T,2T,3T,4T,5T',
    },

    // === ANAK-ANAK (6-12 Tahun) ===
    {
      name: 'Kemeja Anak Laki-Laki Sekolah',
      slug: 'kemeja-anak-laki-laki-sekolah',
      description: 'Kemeja anak laki-laki untuk seragam sekolah dan acara formal. Bahan cotton prima yang rapi dan nyaman dipakai seharian. Warna putih bersih tidak mudah kuning. Tersedia ukuran 6-12 tahun.',
      price: 85000,
      wholesalePrice: 50000,
      minOrder: 24,
      stock: 600,
      images: '/images/products/kemeja-anak.png',
      categoryId: categories[2].id,
      rating: 4.7,
      reviewCount: 534,
      sold: 8900,
      featured: true,
      tags: 'kemeja,anak,sekolah,formal,cotton',
      weight: '150g',
      sizes: '6,7,8,9,10,11,12',
    },
    {
      name: 'Dress Anak Perempuan Casual Cantik',
      slug: 'dress-anak-perempuan-casual-cantik',
      description: 'Dress anak perempuan motif bunga dan polkadot yang cantik. Bahan katun rayon yang sejuk dan nyaman. Desain casual yang cocok untuk harian dan hangout. Tersedia berbagai warna pilihan.',
      price: 115000,
      wholesalePrice: 72000,
      minOrder: 12,
      stock: 400,
      images: '/images/products/dress-anak.png',
      categoryId: categories[2].id,
      rating: 4.8,
      reviewCount: 412,
      sold: 5600,
      featured: true,
      tags: 'dress,anak,perempuan,casual,katun',
      weight: '180g',
      sizes: '6,7,8,9,10,11,12',
    },
    {
      name: 'Kaos Anak Unisex Print Kartun',
      slug: 'kaos-anak-unisex-print-kartun',
      description: 'Kaos anak unisex dengan print kartun dan animasi yang lucu. Bahan cotton combed 24s tebal dan nyaman. Sablon rubber yang awet dan tidak retak. Tersedia 20+ motif pilihan.',
      price: 65000,
      wholesalePrice: 38000,
      minOrder: 24,
      stock: 800,
      images: '/images/products/kaos-anak.png',
      categoryId: categories[2].id,
      rating: 4.6,
      reviewCount: 678,
      sold: 12000,
      featured: false,
      tags: 'kaos,anak,kartun,unisex,cotton',
      weight: '130g',
      sizes: '6,7,8,9,10,11,12',
    },
    {
      name: 'Celana Anak Jeans & Chino Mix',
      slug: 'celana-anak-jeans-chino-mix',
      description: 'Campuran celana jeans dan chino untuk anak. Bahan denim dan cotton twill yang nyaman. Elastis di pinggang untuk ukuran yang fleksibel. Model slim fit dan regular tersedia.',
      price: 95000,
      wholesalePrice: 58000,
      minOrder: 24,
      stock: 500,
      images: '/images/products/celana-anak.png',
      categoryId: categories[2].id,
      rating: 4.5,
      reviewCount: 345,
      sold: 6200,
      featured: false,
      tags: 'celana,anak,jeans,chino,denim',
      weight: '220g',
      sizes: '6,7,8,9,10,11,12',
    },
    {
      name: 'Jaket Anak Hoodie & Bomber',
      slug: 'jaket-anak-hoodie-bomber',
      description: 'Koleksi jaket anak model hoodie dan bomber yang stylish. Bahan fleece dan parasut yang hangat tapi tidak gerah. Warna-warna trendi untuk anak aktif. Cocok untuk pergi sekolah dan jalan-jalan.',
      price: 135000,
      wholesalePrice: 85000,
      minOrder: 12,
      stock: 300,
      images: '/images/products/jaket-anak.png',
      categoryId: categories[2].id,
      rating: 4.7,
      reviewCount: 289,
      sold: 3400,
      featured: true,
      tags: 'jaket,anak,hoodie,bomber,fleece',
      weight: '300g',
      sizes: '6,7,8,9,10,11,12',
    },
    {
      name: 'Gamis Anak Perempuan Syari',
      slug: 'gamis-anak-perempuan-syari',
      description: 'Gamis anak perempuan model syari yang cantik dan sopan. Bahan ceruti dan kaos yang nyaman dipakai seharian. Dilengkapi dengan inner dan jilbit segi empat matching. Cocok untuk harian dan acara.',
      price: 155000,
      wholesalePrice: 98000,
      minOrder: 10,
      stock: 250,
      images: '/images/products/gamis-anak.png',
      categoryId: categories[2].id,
      rating: 4.8,
      reviewCount: 356,
      sold: 4100,
      featured: true,
      tags: 'gamis,anak,syari,muslimah,ceruti',
      weight: '250g',
      sizes: '6,7,8,9,10,11,12',
    },

    // === AKSESORIS BABY KIDS ===
    {
      name: 'Topi Anak Bucket Hat & Cap Set',
      slug: 'topi-anak-bucket-hat-cap-set',
      description: 'Set topi anak model bucket hat dan baseball cap. Bahan katun dan canvas yang nyaman dipakai. Motif kartun dan warna-warna cerah. UV protection untuk melindungi si kecil dari sinar matahari.',
      price: 55000,
      wholesalePrice: 32000,
      minOrder: 24,
      stock: 600,
      images: '/images/products/topi-anak.png',
      categoryId: categories[3].id,
      rating: 4.5,
      reviewCount: 234,
      sold: 4500,
      featured: false,
      tags: 'topi,anak,bucket,cap,kartun',
      weight: '80g',
      sizes: 'S,M,L',
    },
    {
      name: 'Tas Sekolah Anak Karakter',
      slug: 'tas-sekolah-anak-karakter',
      description: 'Tas sekolah anak dengan motif karakter kartun favorit. Bahan polyester 600D yang kuat dan tahan lama. Rongga utama besar dan saku depan. Tali bahu empuk dan ergonomis untuk kenyamanan anak.',
      price: 125000,
      wholesalePrice: 75000,
      minOrder: 12,
      stock: 400,
      images: '/images/products/tas-anak.png',
      categoryId: categories[3].id,
      rating: 4.7,
      reviewCount: 389,
      sold: 5200,
      featured: true,
      tags: 'tas,sekolah,anak,karakter,polyester',
      weight: '400g',
      sizes: 'S,M,L',
    },
    {
      name: 'Ikat Rambut & Aksesoris Bayi Set',
      slug: 'ikat-rambut-aksesoris-bayi-set',
      description: 'Set ikat rambut dan aksesoris bayi lucu. Bahan kain dan plastik aman untuk bayi dan anak. Motif bunga, kupu-kupu, dan karakter kartun. Cocok untuk hadiah dan日常使用.',
      price: 35000,
      wholesalePrice: 18000,
      minOrder: 50,
      stock: 1000,
      images: '/images/products/set-balita.png',
      categoryId: categories[3].id,
      rating: 4.6,
      reviewCount: 567,
      sold: 8900,
      featured: false,
      tags: 'ikat rambut,aksesoris,bayi,lucu,set',
      weight: '50g',
      sizes: 'All Size',
    },

    // === SEPATU ===
    {
      name: 'Sepatu Anak Sneakers Casual',
      slug: 'sepatu-anak-sneakers-casual',
      description: 'Sepatu anak model sneakers casual yang nyaman dan stylish. Bahan mesh dan PU yang breathable dan ringan. Sol karet anti-slip untuk keamanan anak bermain. Velcro dan tali tersedia.',
      price: 155000,
      wholesalePrice: 95000,
      minOrder: 12,
      stock: 350,
      images: '/images/products/sepatu-anak.png',
      categoryId: categories[4].id,
      rating: 4.7,
      reviewCount: 345,
      sold: 4100,
      featured: true,
      tags: 'sepatu,anak,sneakers,casual,mesh',
      weight: '250g',
      sizes: '25,26,27,28,29,30,31,32,33,34,35',
    },
    {
      name: 'Sandal Anak & Slide Anti Slip',
      slug: 'sandal-anak-slide-anti-slip',
      description: 'Sandal anak dan slide model anti-slip untuk keamanan. Bahan EVA dan PVC yang lembut dan ringan. Sol bergerigi untuk cengkeraman kuat. Cocok untuk harian dan ke kolam.',
      price: 55000,
      wholesalePrice: 32000,
      minOrder: 24,
      stock: 700,
      images: '/images/products/sandal-anak.png',
      categoryId: categories[4].id,
      rating: 4.5,
      reviewCount: 267,
      sold: 5800,
      featured: false,
      tags: 'sandal,anak,slide,anti-slip,EVA',
      weight: '120g',
      sizes: '25,26,27,28,29,30,31,32,33,34,35',
    },
    {
      name: 'Sepatu Bayi Pre-Walker Anti Slip',
      slug: 'sepatu-bayi-pre-walker-anti-slip',
      description: 'Sepatu bayi pre-walker dengan sol anti-slip yang aman untuk bayi belajar berjalan. Bahan katun lembut dan breathable. Elastis di pergelangan kaki agar mudah dipasang. Warna-warna lucu dan ceria.',
      price: 75000,
      wholesalePrice: 42000,
      minOrder: 24,
      stock: 500,
      images: '/images/products/romper-bayi.png',
      categoryId: categories[4].id,
      rating: 4.8,
      reviewCount: 456,
      sold: 7200,
      featured: true,
      tags: 'sepatu,bayi,pre-walker,anti-slip,katun',
      weight: '80g',
      sizes: '0-6B,6-12B,12-18B,18-24B',
    },
  ];

  for (const product of products) {
    await db.product.create({
      data: product,
    });
  }

  console.log('✅ Seed completed successfully!');
  console.log(`📦 Created ${categories.length} categories`);
  console.log(`📦 Created ${products.length} products`);
}

main()
  .catch(console.error)
  .finally(() => db.$disconnect());
