import { db } from '@/lib/db';

async function main() {
  // Seed categories
  const categories = await Promise.all([
    db.category.upsert({
      where: { slug: 'bayi-0-2-tahun' },
      update: {},
      create: {
        name: 'Bayi (0-2 Tahun)',
        slug: 'bayi-0-2-tahun',
        description: 'Baju bayi, romper, set bayi lucu dan nyaman untuk si kecil',
        icon: 'Baby',
        image: '/images/categories/bayi.png',
        order: 1,
      },
    }),
    db.category.upsert({
      where: { slug: 'balita-2-5-tahun' },
      update: {},
      create: {
        name: 'Balita (2-5 Tahun)',
        slug: 'balita-2-5-tahun',
        description: 'Pakaian balita lucu dan nyaman untuk aktif bermain',
        icon: 'Smile',
        image: '/images/categories/balita.png',
        order: 2,
      },
    }),
    db.category.upsert({
      where: { slug: 'anak-anak-5-12-tahun' },
      update: {},
      create: {
        name: 'Anak-Anak (5-12 Tahun)',
        slug: 'anak-anak-5-12-tahun',
        description: 'Baju anak untuk sekolah dan santai, model trendi dan nyaman',
        icon: 'GraduationCap',
        image: '/images/categories/anak-anak.png',
        order: 3,
      },
    }),
    db.category.upsert({
      where: { slug: 'remaja-12-17-tahun' },
      update: {},
      create: {
        name: 'Remaja (12-17 Tahun)',
        slug: 'remaja-12-17-tahun',
        description: 'Fashion remaja trendi dan stylish, dari kasual hingga formal',
        icon: 'Sparkles',
        image: '/images/categories/remaja.png',
        order: 4,
      },
    }),
    db.category.upsert({
      where: { slug: 'aksesoris-anak' },
      update: {},
      create: {
        name: 'Aksesoris Anak',
        slug: 'aksesoris-anak',
        description: 'Topi, tas, ikat rambut, dan aksesoris lucu untuk anak',
        icon: 'Crown',
        image: '/images/categories/aksesoris.png',
        order: 5,
      },
    }),
    db.category.upsert({
      where: { slug: 'sepatu-anak' },
      update: {},
      create: {
        name: 'Sepatu Anak & Remaja',
        slug: 'sepatu-anak',
        description: 'Sepatu sekolah, santai, dan olahraga untuk anak dan remaja',
        icon: 'Footprints',
        image: '/images/categories/sepatu.png',
        order: 6,
      },
    }),
  ]);

  // Seed products
  const products = [
    // === BAYI (0-2 Tahun) ===
    {
      name: 'Romper Bayi Set 3in1 Karakter Lucu',
      slug: 'romper-bayi-set-3in1-karakter-lucu',
      description: 'Set romper bayi 3in1 dengan motif karakter hewan lucu. Bahan katun stretch yang lembut dan aman untuk kulit bayi. Mudah dipakai dan dilepas dengan kancing press. Tersedia ukuran 0-6 bulan, 6-12 bulan, 12-18 bulan. Cocok untuk hadiah bayi baru lahir.',
      price: 125000,
      wholesalePrice: 75000,
      minOrder: 12,
      stock: 500,
      images: '/images/products/romper-bayi.png',
      categoryId: categories[0].id,
      rating: 4.9,
      reviewCount: 456,
      sold: 6800,
      featured: true,
      tags: 'romper,bayi,set,lucu,katun',
      weight: '150g',
      sizes: '0-6B,6-12B,12-18B,18-24B',
    },
    {
      name: 'Set Baju Bayi Laki-Laki Casual',
      slug: 'set-baju-bayi-laki-laki-casual',
      description: 'Set baju bayi laki-laki terdiri dari kaos dan celana. Bahan katun combed 30s yang adem dan nyaman. Motif strip dan karikaturnya ganteng. Elastis di pinggang untuk kenyamanan bayi.',
      price: 95000,
      wholesalePrice: 58000,
      minOrder: 12,
      stock: 400,
      images: '/images/products/set-bayi-laki.png',
      categoryId: categories[0].id,
      rating: 4.8,
      reviewCount: 312,
      sold: 4500,
      featured: true,
      tags: 'set,bayi,laki-laki,casual,katun',
      weight: '120g',
      sizes: '0-6B,6-12B,12-18B,18-24B',
    },
    {
      name: 'Dress Bayi Perempuan Floral',
      slug: 'dress-bayi-perempuan-floral',
      description: 'Dress bayi perempuan motif bunga yang cantik dan feminin. Bahan katun rayon yang sejuk dan lembut. Dilengkapi dengan pita dan ruffle di bagian dada. Cocok untuk pesta dan acara spesial si kecil.',
      price: 110000,
      wholesalePrice: 68000,
      minOrder: 12,
      stock: 350,
      images: '/images/products/dress-bayi.png',
      categoryId: categories[0].id,
      rating: 4.9,
      reviewCount: 289,
      sold: 3900,
      featured: true,
      tags: 'dress,bayi,perempuan,floral,pesta',
      weight: '130g',
      sizes: '0-6B,6-12B,12-18B,18-24B',
    },

    // === BALITA (2-5 Tahun) ===
    {
      name: 'Set Baju Balita Laki-Laki Kartun',
      slug: 'set-baju-balita-laki-laki-kartun',
      description: 'Set baju balita laki-laki motif kartun superhero dan dinosaurus. Bahan katun combed yang adem dan tidak panas. Jahitan rapi dan aman untuk anak. Cocok untuk harian dan bermain.',
      price: 105000,
      wholesalePrice: 62000,
      minOrder: 12,
      stock: 450,
      images: '/images/products/baju-balita-laki.png',
      categoryId: categories[1].id,
      rating: 4.7,
      reviewCount: 378,
      sold: 5200,
      featured: true,
      tags: 'set,balita,laki-laki,kartun,katun',
      weight: '150g',
      sizes: '2T,3T,4T,5T',
    },
    {
      name: 'Dress Balita Perempuan Princess Tutu',
      slug: 'dress-balita-perempuan-princess-tutu',
      description: 'Dress balita gaya princess dengan rok tutu yang mengembang. Bahan atas katun dan rok tulle lembut. Cocok untuk pesta ulang tahun dan photo session. Warna pastel yang cantik.',
      price: 145000,
      wholesalePrice: 92000,
      minOrder: 10,
      stock: 300,
      images: '/images/products/dress-balita.png',
      categoryId: categories[1].id,
      rating: 4.9,
      reviewCount: 423,
      sold: 4800,
      featured: true,
      tags: 'dress,balita,princess,tutu,pesta',
      weight: '200g',
      sizes: '2T,3T,4T,5T',
    },
    {
      name: 'Set Baju Balita Unisex Casual',
      slug: 'set-baju-balita-unisex-casual',
      description: 'Set baju balita unisex cocok untuk laki-laki dan perempuan. Desain minimalis modern dengan warna-warna ceria. Bahan cotton combed adem dan menyerap keringat. Easy wash dan tidak mudah luntur.',
      price: 90000,
      wholesalePrice: 54000,
      minOrder: 12,
      stock: 500,
      images: '/images/products/set-balita.png',
      categoryId: categories[1].id,
      rating: 4.6,
      reviewCount: 267,
      sold: 3600,
      featured: false,
      tags: 'set,balita,unisex,casual,cotton',
      weight: '140g',
      sizes: '2T,3T,4T,5T',
    },

    // === ANAK-ANAK (5-12 Tahun) ===
    {
      name: 'Kemeja Anak Laki-Laki Sekolah',
      slug: 'kemeja-anak-laki-laki-sekolah',
      description: 'Kemeja anak laki-laki untuk seragam sekolah dan acara formal. Bahan cotton prima yang rapi dan nyaman dipakai seharian. Warna putih bersih tidak mudah kuning. Tersedia ukuran 5-12 tahun.',
      price: 85000,
      wholesalePrice: 50000,
      minOrder: 24,
      stock: 600,
      images: '/images/products/kemeja-anak.png',
      categoryId: categories[2].id,
      rating: 4.7,
      reviewCount: 534,
      sold: 8900,
      featured: true,
      tags: 'kemeja,anak,sekolah,formal,cotton',
      weight: '150g',
      sizes: '5,6,7,8,9,10,11,12',
    },
    {
      name: 'Dress Anak Perempuan Casual Cantik',
      slug: 'dress-anak-perempuan-casual-cantik',
      description: 'Dress anak perempuan motif bunga dan polkadot yang cantik. Bahan katun rayon yang sejuk dan nyaman. Desain casual yang cocok untuk harian dan hangout. Tersedia berbagai warna pilihan.',
      price: 115000,
      wholesalePrice: 72000,
      minOrder: 12,
      stock: 400,
      images: '/images/products/dress-anak.png',
      categoryId: categories[2].id,
      rating: 4.8,
      reviewCount: 412,
      sold: 5600,
      featured: true,
      tags: 'dress,anak,perempuan,casual,katun',
      weight: '180g',
      sizes: '5,6,7,8,9,10,11,12',
    },
    {
      name: 'Kaos Anak Unisex Print Kartun',
      slug: 'kaos-anak-unisex-print-kartun',
      description: 'Kaos anak unisex dengan print kartun dan animasi yang lucu. Bahan cotton combed 24s tebal dan nyaman. Sablon rubber yang awet dan tidak retak. Tersedia 20+ motif pilihan.',
      price: 65000,
      wholesalePrice: 38000,
      minOrder: 24,
      stock: 800,
      images: '/images/products/kaos-anak.png',
      categoryId: categories[2].id,
      rating: 4.6,
      reviewCount: 678,
      sold: 12000,
      featured: false,
      tags: 'kaos,anak,kartun,unisex,cotton',
      weight: '130g',
      sizes: '5,6,7,8,9,10,11,12',
    },
    {
      name: 'Celana Anak Jeans & Chino Mix',
      slug: 'celana-anak-jeans-chino-mix',
      description: 'Campuran celana jeans dan chino untuk anak. Bahan denim dan cotton twill yang nyaman. Elastis di pinggang untuk ukuran yang fleksibel. Model slim fit dan regular tersedia.',
      price: 95000,
      wholesalePrice: 58000,
      minOrder: 24,
      stock: 500,
      images: '/images/products/celana-anak.png',
      categoryId: categories[2].id,
      rating: 4.5,
      reviewCount: 345,
      sold: 6200,
      featured: false,
      tags: 'celana,anak,jeans,chino,denim',
      weight: '220g',
      sizes: '5,6,7,8,9,10,11,12',
    },
    {
      name: 'Jaket Anak Hoodie & Bomber',
      slug: 'jaket-anak-hoodie-bomber',
      description: 'Koleksi jaket anak model hoodie dan bomber yang stylish. Bahan fleece dan parasut yang hangat tapi tidak gerah. Warna-warna trendi untuk anak aktif. Cocok untuk pergi sekolah dan jalan-jalan.',
      price: 135000,
      wholesalePrice: 85000,
      minOrder: 12,
      stock: 300,
      images: '/images/products/jaket-anak.png',
      categoryId: categories[2].id,
      rating: 4.7,
      reviewCount: 289,
      sold: 3400,
      featured: true,
      tags: 'jaket,anak,hoodie,bomber,fleece',
      weight: '300g',
      sizes: '5,6,7,8,9,10,11,12',
    },
    {
      name: 'Gamis Anak Perempuan Syari',
      slug: 'gamis-anak-perempuan-syari',
      description: 'Gamis anak perempuan model syari yang cantik dan sopan. Bahan ceruti dan kaos yang nyaman dipakai seharian. Dilengkapi dengan inner dan jilbit segi empat matching. Cocok untuk harian dan acara.',
      price: 155000,
      wholesalePrice: 98000,
      minOrder: 10,
      stock: 250,
      images: '/images/products/gamis-anak.png',
      categoryId: categories[2].id,
      rating: 4.8,
      reviewCount: 356,
      sold: 4100,
      featured: true,
      tags: 'gamis,anak,syari,muslimah,ceruti',
      weight: '250g',
      sizes: '5,6,7,8,9,10,11,12',
    },

    // === REMAJA (12-17 Tahun) ===
    {
      name: 'Kaos Remaja Oversize Streetwear',
      slug: 'kaos-remaja-oversize-streetwear',
      description: 'Kaos remaja model oversize gaya streetwear yang lagi trending. Bahan cotton combed 24s yang tebal dan jatuh. Sablon DTF berkualitas tinggi yang tidak luntur. Tersedia 30+ desain kekinian.',
      price: 85000,
      wholesalePrice: 48000,
      minOrder: 24,
      stock: 700,
      images: '/images/products/kaos-remaja.png',
      categoryId: categories[3].id,
      rating: 4.7,
      reviewCount: 567,
      sold: 9800,
      featured: true,
      tags: 'kaos,remaja,oversize,streetwear,cotton',
      weight: '200g',
      sizes: 'S,M,L,XL,XXL',
    },
    {
      name: 'Hoodie Remaja Trendy Premium',
      slug: 'hoodie-remaja-trendy-premium',
      description: 'Hoodie remaja premium bahan fleece yang tebal dan hangat. Model kangguru pocket dengan tali hood adjustable. Bordir dan sablon berkualitas. Warna-warna aesthetic yang kekinian.',
      price: 165000,
      wholesalePrice: 105000,
      minOrder: 12,
      stock: 350,
      images: '/images/products/hoodie-remaja.png',
      categoryId: categories[3].id,
      rating: 4.8,
      reviewCount: 423,
      sold: 5600,
      featured: true,
      tags: 'hoodie,remaja,trendy,fleece,premium',
      weight: '400g',
      sizes: 'S,M,L,XL,XXL',
    },
    {
      name: 'Dress Remaja Casual Modern',
      slug: 'dress-remaja-casual-modern',
      description: 'Dress remaja model casual modern yang chic dan stylish. Bahan katun rayon dan viskose yang jatuh dan sejuk. Motif bunga dan solid color tersedia. Cocok untuk hangout dan acara casual.',
      price: 145000,
      wholesalePrice: 88000,
      minOrder: 12,
      stock: 300,
      images: '/images/products/dress-remaja.png',
      categoryId: categories[3].id,
      rating: 4.7,
      reviewCount: 312,
      sold: 3800,
      featured: false,
      tags: 'dress,remaja,casual,modern,katun',
      weight: '200g',
      sizes: 'S,M,L,XL',
    },
    {
      name: 'Kemeja Remaja Laki-Laki Stylish',
      slug: 'kemeja-remaja-laki-laki-stylish',
      description: 'Kemeja remaja laki-laki model casual dan semi-formal. Bahan cotton dan linen premium yang adem. Motif kotak-kotak dan solid tersedia. Cocok untuk ke kampus, hangout, dan acara.',
      price: 135000,
      wholesalePrice: 82000,
      minOrder: 12,
      stock: 350,
      images: '/images/products/kemeja-remaja.png',
      categoryId: categories[3].id,
      rating: 4.6,
      reviewCount: 267,
      sold: 3200,
      featured: false,
      tags: 'kemeja,remaja,laki-laki,stylish,cotton',
      weight: '180g',
      sizes: 'S,M,L,XL,XXL',
    },
    {
      name: 'Celana Remaja Cargo & Jeans',
      slug: 'celana-remaja-cargo-jeans',
      description: 'Celana cargo dan jeans remaja model baggy dan wide leg yang trending. Bahan denim dan cotton twill berkualitas. Saku cargo fungsional dan stylish. Wash effect yang kekinian.',
      price: 155000,
      wholesalePrice: 95000,
      minOrder: 12,
      stock: 400,
      images: '/images/products/celana-remaja.png',
      categoryId: categories[3].id,
      rating: 4.7,
      reviewCount: 345,
      sold: 4500,
      featured: true,
      tags: 'celana,remaja,cargo,jeans,baggy',
      weight: '350g',
      sizes: 'S,M,L,XL,XXL',
    },
    {
      name: 'Jaket Remaja Bomber & Denim',
      slug: 'jaket-remaja-bomber-denim',
      description: 'Jaket remaja koleksi bomber dan denim yang keren. Bahan parasut waterproof dan denim premium. Variasi bordir dan patch yang unik. Warna-warna bold dan aesthetic.',
      price: 195000,
      wholesalePrice: 128000,
      minOrder: 10,
      stock: 250,
      images: '/images/products/jaket-remaja.png',
      categoryId: categories[3].id,
      rating: 4.8,
      reviewCount: 234,
      sold: 2900,
      featured: true,
      tags: 'jaket,remaja,bomber,denim,stylish',
      weight: '450g',
      sizes: 'S,M,L,XL,XXL',
    },
    {
      name: 'Gamis Remaja Muslimah Modern',
      slug: 'gamis-remaja-muslimah-modern',
      description: 'Gamis remaja model modern dan syari yang elegan. Bahan ceruti, kaos, dan wolfis premium. Aksen payet dan bordir yang cantik. Dilengkapi inner dan jilbit segi empat matching.',
      price: 185000,
      wholesalePrice: 118000,
      minOrder: 10,
      stock: 280,
      images: '/images/products/gamis-remaja.png',
      categoryId: categories[3].id,
      rating: 4.9,
      reviewCount: 456,
      sold: 5800,
      featured: true,
      tags: 'gamis,remaja,muslimah,modern,syari',
      weight: '300g',
      sizes: 'S,M,L,XL,XXL',
    },

    // === AKSESORIS ANAK ===
    {
      name: 'Topi Anak Bucket Hat & Cap Set',
      slug: 'topi-anak-bucket-hat-cap-set',
      description: 'Set topi anak model bucket hat dan baseball cap. Bahan katun dan canvas yang nyaman dipakai. Motif kartun dan warna-warna cerah. UV protection untuk melindungi si kecil dari sinar matahari.',
      price: 55000,
      wholesalePrice: 32000,
      minOrder: 24,
      stock: 600,
      images: '/images/products/topi-anak.png',
      categoryId: categories[4].id,
      rating: 4.5,
      reviewCount: 234,
      sold: 4500,
      featured: false,
      tags: 'topi,anak,bucket,cap,kartun',
      weight: '80g',
      sizes: 'S,M,L',
    },
    {
      name: 'Tas Sekolah Anak Karakter',
      slug: 'tas-sekolah-anak-karakter',
      description: 'Tas sekolah anak dengan motif karakter kartun favorit. Bahan polyester 600D yang kuat dan tahan lama. Rongga utama besar dan saku depan. Tali bahu empuk dan ergonomis untuk kenyamanan anak.',
      price: 125000,
      wholesalePrice: 75000,
      minOrder: 12,
      stock: 400,
      images: '/images/products/tas-anak.png',
      categoryId: categories[4].id,
      rating: 4.7,
      reviewCount: 389,
      sold: 5200,
      featured: true,
      tags: 'tas,sekolah,anak,karakter,polyester',
      weight: '400g',
      sizes: 'S,M,L',
    },

    // === SEPATU ANAK ===
    {
      name: 'Sepatu Anak Sneakers Casual',
      slug: 'sepatu-anak-sneakers-casual',
      description: 'Sepatu anak model sneakers casual yang nyaman dan stylish. Bahan mesh dan PU yang breathable dan ringan. Sol karet anti-slip untuk keamanan anak bermain. Velcro dan tali tersedia.',
      price: 155000,
      wholesalePrice: 95000,
      minOrder: 12,
      stock: 350,
      images: '/images/products/sepatu-anak.png',
      categoryId: categories[5].id,
      rating: 4.7,
      reviewCount: 345,
      sold: 4100,
      featured: true,
      tags: 'sepatu,anak,sneakers,casual,mesh',
      weight: '250g',
      sizes: '25,26,27,28,29,30,31,32,33,34,35',
    },
    {
      name: 'Sandal Anak & Slide Anti Slip',
      slug: 'sandal-anak-slide-anti-slip',
      description: 'Sandal anak dan slide model anti-slip untuk keamanan. Bahan EVA dan PVC yang lembut dan ringan. Sol bergerigi untuk cengkeraman kuat. Cocok untuk harian dan ke kolam.',
      price: 55000,
      wholesalePrice: 32000,
      minOrder: 24,
      stock: 700,
      images: '/images/products/sandal-anak.png',
      categoryId: categories[5].id,
      rating: 4.5,
      reviewCount: 267,
      sold: 5800,
      featured: false,
      tags: 'sandal,anak,slide,anti-slip,EVA',
      weight: '120g',
      sizes: '25,26,27,28,29,30,31,32,33,34,35',
    },
    {
      name: 'Sepatu Remaja Sneakers Trendy',
      slug: 'sepatu-remaja-sneakers-trendy',
      description: 'Sepatu remaja model sneakers trendy gaya streetwear. Bahan mesh premium dan sol cushion yang nyaman untuk seharian. Desain kekinian yang cocok untuk ootd. Tersedia warna-warna aesthetic.',
      price: 225000,
      wholesalePrice: 148000,
      minOrder: 10,
      stock: 250,
      images: '/images/products/sepatu-remaja.png',
      categoryId: categories[5].id,
      rating: 4.8,
      reviewCount: 312,
      sold: 3600,
      featured: true,
      tags: 'sepatu,remaja,sneakers,trendy,streetwear',
      weight: '350g',
      sizes: '36,37,38,39,40,41,42',
    },
  ];

  for (const product of products) {
    await db.product.upsert({
      where: { slug: product.slug },
      update: {},
      create: product,
    });
  }

  console.log('✅ Seed completed successfully!');
  console.log(`📦 Created ${categories.length} categories`);
  console.log(`📦 Created ${products.length} products`);
}

main()
  .catch(console.error)
  .finally(() => db.$disconnect());
